{% set version = "0.5.1" %}

package:
  name: go-eclint
  version: {{ version }}

source:
  url: https://gitlab.com/greut/eclint/-/archive/v{{ version }}/eclint-v{{ version }}.tar.gz
  sha256: 0db3e023fdc0c8fa3487faf7daf4e021e32820cd4ae6ab3a2b51b770142ee72e

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - eclint --help

about:
  home: https://github.com/greut/eclint
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A faster alternative to the JavaScript eclint written in Go.
  dev_url: https://github.com/greut/eclint

extra:
  recipe-maintainers:
    - danielnachun
