schema_version: 1

context:
  version: "0.5.2"

package:
  name: go-eclint
  version: ${{ version }}

source:
  url: https://gitlab.com/greut/eclint/-/archive/v${{ version }}/eclint-v${{ version }}.tar.gz
  sha256: 0a9cc7fda855cc1ebadc3dee58db49a8cd859ef219ee6c205ec89ef53cc63896

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - eclint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A faster alternative to the JavaScript eclint written in Go.
  homepage: https://github.com/greut/eclint
  repository: https://github.com/greut/eclint

extra:
  recipe-maintainers:
    - danielnachun
